language: rust
dist: trusty
rust: nightly
sudo: required

addons:
  apt:
    packages:
    - libportaudio-dev
    - libsdl2-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev

install:
  - wget http://download.nanomsg.org/nanomsg-0.5-beta.tar.gz
  - tar -xvzf nanomsg-0.5-beta.tar.gz
  - ( cd nanomsg-0.5-beta && ./configure && make && sudo make install )
  - sudo ldconfig

script:
  - ( for dir in $(find . -name  'Cargo.toml' | sed 's/Cargo\.toml$//'); do ( echo "$dir" && cd "$dir" && cargo build --verbose ); done )
