language: rust
dist: trusty
rust: nightly
sudo: required

addons:
  apt:
    packages:
    - libportaudio-dev
    - libsdl2-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev
    - cmake

install:
  - wget https://github.com/nanomsg/nanomsg/archive/1.1.2.tar.gz
  - tar -xvzf 1.1.2.tar.gz
  - ( cd nanomsg-1.1.2 && mkdir build && cd build && cmake .. && sudo cmake --build . --target install && sudo ldconfig )

script:
  - ( for file in $(find . -name  'Cargo.toml'); do ( echo "Building $file" && cd "$(dirname $file)" && cargo build --verbose ); done )
