language: rust
dist: trusty
rust: nightly
sudo: required

addons:
  apt:
    packages:
    - libportaudio-dev
    - libsdl2-dev
    - libsdl2-mixer-jev
    - libsdl2-ttf-dev

install:
  - wget https://github.com/nanomsg/nanomsg/archive/1.1.2.tar.gz
  - tar -xvzf 1.1.2-tar.gz
  - ( cd nanomsg-1.1.2 && sudo cmake --build . --target install )

script:
  - ( for dir in $(find . -name  'Cargo.toml' | sed 's/Cargo\.toml$//'); do ( echo "$dir" && cd "$dir" && cargo build --verbose ); done )
