language: rust
dist: trusty
rust: nightly
sudo: required

addons:
  apt:
    packages:
    - libportaudio-dev
    - libsdl2-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev

install:
  - wget http://download.nanomsg.org/nanomsg-0.5-beta.tar.gz
  - tar -xvzf nanomsg-0.5-beta.tar.gz
  - ( cd nanomsg-0.5-beta && ./configure && make && sudo make install )
  - sudo ldconfig

script:
  - ( cargo build --verbose )
  - ( cd client/bin && cargo build --verbose )
  - ( cd server/bin && cargo build --verbose )
  - ( cd common     && cargo test  --verbose )
  - ( cd client/lib && cargo test  --verbose )
  - ( cd server/lib && cargo test  --verbose )
