[package]

name = "playform-common"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
  "Clark Gaebel <cg.wowus.cg@gmail.com>",
  "Elijah Andrews <elijahcandrews@gmail.com>",
]

[lib]
name = "common"
path = "mod.rs"

[dependencies]
cgmath         = { version = "0.14.*", features = ["eders"] }
collision      = { version = "0.10.*", features = ["eders"] }
fnv            = "*"
log            = "*"
nanomsg        = "*"
num            = "*"
serde          = "*"
serde_derive   = "*"
time           = "*"

[dependencies.voxel-data]
git = "https://github.com/bfops/rust-voxel-data"

[dependencies.isosurface-extraction]
git = "https://github.com/bfops/rust-isosurface-extraction"
